name: Build OpenWrt ethernet drivers

# on: [push, pull_request]
on:
  push:
    branches:
      - 'main'

jobs:
  build_Modules:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        sdk_url:
            - https://downloads.immortalwrt.org/releases/21.02.5/targets/x86/64/immortalwrt-sdk-21.02.5-x86-64_gcc-8.4.0_musl.Linux-x86_64.tar.xz

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install $(curl -fsSL $APT_URL) tree
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean

    - name: Download SDK
      run: |
        url=${{ matrix.sdk_url }}
        sdk=$(basename $url | awk -F '.tar.xz' '{ print $1 }')

        wget $url
        tar xvf $sdk.tar.xz

        mkdir -p $sdk/package
        cp -r drivers/* $sdk/package/

    - name: Compile
      run: |
        url=${{ matrix.sdk_url }}
        sdk=$(basename $url | awk -F '.tar.xz' '{ print $1 }')

        cd $sdk
        echo 'CONFIG_PACKAGE_kmod-igb-intel=m' >> .config
        make defconfig
        
        make package/kmod-igb-intel/compile -j$(nproc) || make package/kmod-igb-intel/compile -j1 V=sc || exit 0

        # cp file to artifact
        cd ${{ github.workspace }}
        mkdir -p ${{ github.workspace }}/artifact

        for ipk in `find . -name 'kmod-igb-intel*.ipk'`; do
          cp $ipk ${{ github.workspace }}/artifact
        done

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.KMOD_VERSION }}
        path: ${{ github.workspace }}/artifact/**/*

  deploy:
    needs: [build_Modules]
    name: Create release and upload artifacts
    runs-on: ubuntu-latest

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ env.KMOD_VERSION }}

    - name: Upload buildinfo
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_buildinfo
        path: ./artifact/buildinfo/

    - name: Upload package
      uses: actions/upload-artifact@v2
      with:
        name: OpenWrt_package
        path: ./artifact/package/
